### ISSUE TITLE
device_session_id la longitud tiene que estar entre 0 y 32

### ISSUE THREAD

**Issue by lorenzolopez928** [open-pay/openpay-android#11]
I am getting this response from the openpay sandbox

{ http_code: 400,
  error_code: 1001,
  category: 'request',
  description: 'device_session_id la longitud tiene que estar entre 0 y 32',
  request_id: '02acc04c-09e0-4e2c-9358-25d4c9bd0ca7' }

The device_session_id variable is generated according to the openpay android sdk.

How can be this posible?

**Comment by hugohernandez** [comment]
Hello,

We just released version 2.0.3 that corrects this incompatibility.

Greetings.

**Comment by lorenzolopez928** [comment]
Todavia no esta publicada la sdk en formato aar.

**Comment by hugohernandez** [comment]
Hola,

La librería aar esta dentro del archivo zip.

https://github.com/open-pay/openpay-android/releases
SDK-v2.0.3.zip

Saludos.
