### ISSUE TITLE
Problemas cuando se genera el apk en debug y release

### ISSUE THREAD

**Issue by DevKhalydIOS** [open-pay/openpay-android#14]
Cuando trato de instalar un apk en modo release la app crashea al momento de llegar a la parte de openpay. Pero si lo instalo en modo debug la app funciona sin problema. Mi pregunta aqui es si se necesita hacer una configuracion mas para openpay o el error es mio.

**Comment by Leay15** [comment]
@DevKhalydIOS Ya revisaste que no estes realizando ofuscacion de codigo en modo release? Si es asi, necesitas agregar las reglas al archivo proguard-rules.pro

**Comment by AlbertoMarin2** [comment]
@Leay15 crees que puedas proporcionar las reglas del archivo, ya que de igual manera tengo en este mismo problema al momento de crear el apk en release

**Comment by Leay15** [comment]
en el issue/#2 hicieron favor de compartir algunas reglas, se las resumo a continuacion:

```
-keepnames class org.codehaus.jackson.** { *; }
-dontwarn org.codehaus.jackson.**

-keepnames class com.google.** { *; }
-dontwarn com.google.**

-keepnames class org.apache.commons.** { *; }
-dontwarn org.apache.commons.**

-keepnames class org.apache.http.** { *; }
-dontwarn org.apache.http.**

-keep class mx.openpay.android.* {;}
```
