### ISSUE TITLE
Pudieran compartir la configuración para proGuard?

### ISSUE THREAD

**Issue by morfin** [open-pay/openpay-android#2]
Se presentan algunos conflictos con proGuard. 

Tendrán las instrucciones para el archivo proguard-rules.txt ?

Gracias.

**Comment by rockar06** [comment]
¿Has encontrado la solución para el proguard? Tengo problemas con el mismo tema.

**Comment by rahulpawar31** [comment]
Estoy teniendo el mismo problema al crear la versión de lanzamiento.

**Comment by rahulpawar31** [comment]
Solved this issue by adding below pro guard entries : 
```
-keepnames class org.codehaus.jackson.** { *; }
-dontwarn org.codehaus.jackson.**

-keepnames class com.google.** { *; }
-dontwarn com.google.**

-keepnames class org.apache.commons.** { *; }
-dontwarn org.apache.commons.**

-keepnames class org.apache.http.** { *; }
-dontwarn org.apache.http.**
```

**Comment by aldorodz** [comment]
Mi app fallaba en release por lo cual me la rechazaron en la validación de OpenPay. Les comparto otra línea de proguard por si alguien la pasa igual :

`-keep class mx.openpay.android.** {*;}`
