### ISSUE TITLE
Podrían proveer instalación usando gradle?

### ISSUE THREAD

**Issue by wmoisesd** [open-pay/openpay-android#3]
es como obsoleto tener que hacer todo un proceso cuando pudiera ser tan simple como agregar una linea en Gradle...

**Comment by LuisRodriguezLD** [comment]
+1

**Comment by David2913** [comment]
Creo lo mismo, son varios pasos. Se vuelve complicado sobre todo si se quiere implementar esta librería en ReactNative o incluirla como dependencia de otra librería. El proceso importando AAR es un poco obsoleto

**Comment by Fransebas** [comment]
Yo no encuentro el AAR, ¿dónde lo descargo? o ¿tengo que compilarlo yo?

**Comment by David2913** [comment]
@Fransebas tienes que descargar el archivo SDK-v2.0.0.zip dentro de la pestaña de releases: https://github.com/open-pay/openpay-android/releases

**Comment by Fransebas** [comment]
@David2913 gracias, me siento tonto pero de verdad no lo encontraba

**Comment by Petruccini** [comment]
Por favor! Es ya bastante obsoleto tener que agregar el AAR

**Comment by jemy-dasm-openpay** [comment]
Lamentamos los inconvenientes causados, ya está en revisión este tema.
