### ISSUE TITLE
minSdkVersion 19

### ISSUE THREAD

**Issue by eitanaviv** [open-pay/openpay-android#7]
Hi there,
I'm using your library as part of my project and wondered why minSdkVersion is set to 19? I had to change my project's minSdkVersion from 17 to 19.
Does your library have a limitation that requires to have minSdkVersion 19?
Thanks!

**Comment by jemy-dasm-openpay** [comment]
We are closing this issue because there have been many updates since it was opened.

Hopefully you're not having this issue anymore but if there are problems still happening please let us know and we'll open this issue again.

Cheers!
