### ISSUE TITLE
Generar cargos

### ISSUE THREAD

**Issue by PakitoConK** [open-pay/openpay-android#8]
Hola, he seguido los pasos y todo bien, pero ¿como puedo generar o que tipo de variable debo declarar para generar el cargo a tarjeta?

Gracias :)

**Comment by Monoradioactivo** [comment]
@PakitoConK ésta librería es una librería cliente, para poder procesar un cargo es necesario que lo haga desde su backend. Openpay ofrece distintas librerías servidor https://openpay.mx/docs/libraries.html

**Comment by jjge1824** [comment]
Hola, al tratar de usar el metodo createCard me sale el error Method POST is not allowed with Public key y en su documentación no dice nada al respecto, inclusive su App de ejemplo se encuentra usando ese metodo. ¿Cuál es la razón y como lo arreglo?

**Comment by jemy-dasm-openpay** [comment]
Ya es posible siguiendo la documentación el hacer un cargo a tarjeta.
