### ISSUE TITLE
Method POST is not allowed with Public key con función createCard

### ISSUE THREAD

**Issue by jjge1824** [open-pay/openpay-android#9]
Hola, al tratar de usar el metodo createCard me sale el error Method POST is not allowed with Public key y en su documentación no dice nada al respecto, inclusive su App de ejemplo se encuentra usando ese metodo. ¿Cuál es la razón y como lo arreglo?

**Comment by GreenSmile** [comment]
We are having the same issue as well. Guys, could you please explain what is the reason for it?

**Comment by hugohernandez** [comment]
Hola,

El método "createCard" ha sido deprecado, favor de usar "createToken".

Hi,

The "createCard" method has been deprecated, please use "createToken".
